[build]
  publish = "."             # or "public" if that’s your static folder
  functions = "netlify/functions"

[[redirects]]
  from = "/feedback-form/*"
  to   = "https://form.asana.com/:splat"
  status = 200
  force  = true
  headers = { 
    # let browsers send your site’s cookies along
    "Access-Control-Allow-Origin" = "https://nexusclimate.co",
    "Access-Control-Allow-Credentials" = "true"
  }