[build]
  publish = "."

# proxy all static files
[[redirects]]
  from   = "/feedback-form/static/*"
  to     = "https://form.asana.com/static/:splat"
  status = 200
  force  = true

# proxy everything else under /feedback-form/
[[redirects]]
  from   = "/feedback-form/*"
  to     = "https://form.asana.com/:splat"
  status = 200
  force  = true